# Generated by Django 5.1.1 on 2024-10-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'alumnos'},
        ),
        migrations.AlterModelTable(
            name='alumno',
            table='alumnos',
        ),
    ]
